Repository DawnBee/college-medicine-app, pull requests merged in 2024-06, with the labels that each got.

#66 Implemented mobile 'nav-menu' 📱
  backend/backend/__pycache__/settings.cpython-312.pyc
  frontend/src/components/Navbar.jsx
  frontend/src/components/PublicationDetail.jsx
  frontend/src/styles/Main.css
  frontend/src/styles/Main.css.map
  frontend/src/styles/Main.sass
Labels: documentation, enhancement, testing

#68 Testing with dummy data
  backend/media/benefactors/student-1.jpg
  backend/media/benefactors/student-3.jpg
  backend/media/faculties/analyza-bg-red.png
  backend/media/faculties/darwiza-bg-red.png
  backend/media/faculties/edwin-bg-red.png
  backend/media/faculties/eva-bg-red.png
  backend/media/faculties/jocelyn-bg-red.png
  backend/media/faculties/romeo-bg-red.png
  backend/media/faculties/shilrose-bg-red.png
  backend/media/faculties/vien-bg-red.png
  backend/media/org_chart/library-building.jpg
  backend/media/org_chart/org-chart.jpg
  backend/media/trainings/sim-3.jpg
  backend/media/trainings/sim-4.jpg
Labels: testing

#76 Added new tab in Mannequin Cards
  backend/media/trainings/doctors-meeting.jpg
  frontend/src/components/MannequinCards.jsx
Labels: documentation, enhancement

#78 Removed 'search' in navbar
  frontend/src/components/Navbar.jsx
Labels: bug, enhancement

#79 Added "read more" in history section
  frontend/src/components/History.jsx
  frontend/src/pages/About.jsx
  frontend/src/styles/Main.css
  frontend/src/styles/Main.css.map
  frontend/src/styles/Main.sass
  frontend/src/styles/_mixins.sass
Labels: enhancement

#80 Fixed @mixin terminal issue
  frontend/src/styles/Main.css
  frontend/src/styles/Main.css.map
  frontend/src/styles/_mixins.sass
Labels: bug

#81 Added 'Lecturers' section in 'Faculty' page
  backend/faculty/__pycache__/admin.cpython-312.pyc
  backend/faculty/__pycache__/models.cpython-312.pyc
  backend/faculty/__pycache__/serializers.cpython-312.pyc
  backend/faculty/__pycache__/urls.cpython-312.pyc
  backend/faculty/__pycache__/views.cpython-312.pyc
  backend/faculty/admin.py
  backend/faculty/migrations/0002_lecturers.py
  backend/faculty/migrations/__pycache__/0002_lecturers.cpython-312.pyc
  backend/faculty/models.py
  backend/faculty/serializers.py
  backend/faculty/urls.py
  backend/faculty/views.py
  frontend/src/components/Faculties.jsx
  frontend/src/components/History.jsx
  frontend/src/components/Lecturers.jsx
  frontend/src/pages/Faculty.jsx
  frontend/src/styles/Main.css
  frontend/src/styles/Main.css.map
  frontend/src/styles/Main.sass
Labels: documentation, enhancement

#94 Removed description on 'Benefactor Cards'
  backend/about/__pycache__/models.cpython-312.pyc
  backend/about/migrations/0002_alter_benefactors_options_remove_benefactors_content_and_more.py
  backend/about/migrations/__pycache__/0002_alter_benefactors_options_remove_benefactors_content_and_more.cpython-312.pyc
  backend/about/models.py
  backend/media/benefactors/student-1.jpg
  backend/media/benefactors/student-4.jpg
  backend/media/benefactors/student-4_OCXCPxe.jpg
  frontend/src/components/Benefactors.jsx
  frontend/src/styles/Main.css
  frontend/src/styles/Main.css.map
  frontend/src/styles/Main.sass
Labels: documentation, enhancement, testing

#95 Fixed typography in "payment-fee" section
  frontend/src/pages/Admission.jsx
  frontend/src/styles/Main.css
  frontend/src/styles/Main.css.map
  frontend/src/styles/Main.sass
Labels: enhancement, testing

#98 Recycled 'Alumni' to become 'Others' page
  frontend/src/App.jsx
  frontend/src/components/CommunityActivities.jsx
  frontend/src/components/Gallery.jsx
  frontend/src/components/Navbar.jsx
  frontend/src/components/OfficerCards.jsx
  frontend/src/components/OfficerSearch.jsx
  frontend/src/components/Sidebar.jsx
  frontend/src/components/Spotlight.jsx
  frontend/src/pages/Others.jsx
  frontend/src/styles/Main.css
  frontend/src/styles/Main.css.map
  frontend/src/styles/Main.sass
Labels: documentation, enhancement, testing

#96 Added 'logo' on tab
  frontend/index.html
Labels: enhancement, testing

#97 Renamed 'Quotes' slider to 'Highlights'
  frontend/src/components/Highlights.jsx
  frontend/src/pages/Faculty.jsx
  frontend/src/styles/Main.css
  frontend/src/styles/Main.sass
Labels: enhancement, testing

#100 Re-structure 'Scholarship' section
  frontend/src/components/Scholarship.jsx
  frontend/src/pages/Admission.jsx
  frontend/src/styles/Main.css
  frontend/src/styles/Main.css.map
  frontend/src/styles/Main.sass
  frontend/src/styles/_mixins.sass
Labels: documentation, enhancement, testing

#101 Revert "Re-structure 'Scholarship' section"
  frontend/src/components/Scholarship.jsx
  frontend/src/pages/Admission.jsx
  frontend/src/styles/Main.css
  frontend/src/styles/Main.css.map
  frontend/src/styles/Main.sass
  frontend/src/styles/_mixins.sass
Labels: help wanted, invalid

#102 Revert "Revert "Re-structure 'Scholarship' section""
  frontend/src/components/Scholarship.jsx
  frontend/src/pages/Admission.jsx
  frontend/src/styles/Main.css
  frontend/src/styles/Main.css.map
  frontend/src/styles/Main.sass
  frontend/src/styles/_mixins.sass
Labels: help wanted, testing

#103 Added 'wooden background' on 'Highlights' slider
  frontend/src/assets/images/wooden-theme.png
  frontend/src/components/Scholarship.jsx
  frontend/src/styles/Main.css
  frontend/src/styles/Main.css.map
  frontend/src/styles/Main.sass
Labels: enhancement, testing

#104 Modified dropdown links
  frontend/src/components/Navbar.jsx
Labels: enhancement, testing

#105 Added 'Curriculum' section in 'About' page
  backend/about/__pycache__/admin.cpython-312.pyc
  backend/about/__pycache__/models.cpython-312.pyc
  backend/about/__pycache__/serializers.cpython-312.pyc
  backend/about/__pycache__/urls.cpython-312.pyc
  backend/about/__pycache__/views.cpython-312.pyc
  backend/about/admin.py
  backend/about/migrations/0003_curriculum.py
  backend/about/migrations/__pycache__/0003_curriculum.cpython-312.pyc
  backend/about/models.py
  backend/about/serializers.py
  backend/about/urls.py
  backend/about/views.py
  backend/faculty/__pycache__/models.cpython-312.pyc
  backend/faculty/models.py
  backend/media/curriculum/Curriculum-2023_SrzgXQn.pdf
  frontend/src/components/Curriculum.jsx
  frontend/src/pages/About.jsx
  frontend/src/styles/Main.css
  frontend/src/styles/Main.css.map
  frontend/src/styles/Main.sass
Labels: documentation, testing

#110 Modified styling on 'Benefactor Cards"
  frontend/src/components/Benefactors.jsx
  frontend/src/styles/Main.css
  frontend/src/styles/Main.css.map
  frontend/src/styles/Main.sass
Labels: enhancement, testing

#111 Re-structured 'Values' section in 'About' page
  backend/about/admin.py
  backend/about/migrations/0004_delete_values.py
  backend/about/models.py
  backend/about/serializers.py
  backend/about/urls.py
  backend/about/views.py
  backend/faculty/migrations/0003_alter_orgchart_options.py
  frontend/src/components/Values.jsx
  frontend/src/styles/Main.css
  frontend/src/styles/Main.css.map
  frontend/src/styles/Main.sass
Labels: enhancement, testing

#112 Fix typo on banner and footer 🔧
  frontend/src/components/Footer.jsx
  frontend/src/components/ParallaxBanner.jsx
Labels: bug, enhancement

#113 Added an 'Email Button' in 'Admission' page
  frontend/src/components/EmailButton.jsx
  frontend/src/pages/Admission.jsx
Labels: enhancement, wontfix, testing

#114 Added 'detail' & 'list' pages on components in 'Others' page
  backend/backend/settings.py
  backend/backend/urls.py
  backend/media/news/event-3.jpg
  backend/media/news/event-3_Sy7XvKa.jpg
  backend/media/news/event-4.jpeg
  backend/media/officers/student-1_9h4uz6n.jpg
  backend/media/officers/student-3.jpg
  backend/media/officers/student-4.jpg
  backend/others/__init__.py
  backend/others/admin.py
  backend/others/apps.py
  backend/others/migrations/0001_initial.py
  backend/others/migrations/0002_activities_news.py
  backend/others/migrations/0003_alter_activities_name_alter_news_title.py
  backend/others/migrations/__init__.py
  backend/others/models.py
  backend/others/serializers.py
  backend/others/tests.py
  backend/others/urls.py
  backend/others/views.py
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/components/Activities.jsx
  frontend/src/components/CommunityActivities.jsx
  frontend/src/components/Curriculum.jsx
  frontend/src/components/News.jsx
  frontend/src/components/OfficerCards.jsx
  frontend/src/components/OfficerDetail.jsx
  frontend/src/components/OfficerList.jsx
  frontend/src/components/Sidebar.jsx
  frontend/src/components/Values.jsx
  frontend/src/styles/Detail.css
  frontend/src/styles/Detail.css.map
  frontend/src/styles/Detail.sass
  frontend/src/styles/Main.css
  frontend/src/styles/Main.css.map
  frontend/src/styles/Main.sass
Labels: documentation, enhancement, testing

#116 Added 'search-bar' functionality 🔍
  backend/media/officers/student-2.jpg
  backend/others/utils.py
  backend/others/views.py
  frontend/src/components/OfficerSearch.jsx
  frontend/src/styles/Main.css
  frontend/src/styles/Main.css.map
  frontend/src/styles/Main.sass
Labels: documentation, enhancement, testing

#123 Fixed 'key prop' error in 'OfficerSearch'
  backend/media/publications/coronavirus_HKceJw1.jpg
  backend/media/publications/follicular-dendritic-cell.png
  backend/media/publications/postpandrial-peaking....png
  backend/media/publications/succinate-dehydrogenase..._VKSkH1k.png
  frontend/src/components/OfficerSearch.jsx
Labels: bug

#124 Added college email on 'Contact Us' button
  frontend/src/components/EmailButton.jsx
Labels: documentation, enhancement

#125 Added content to 'Home' page
  backend/home/models.py
  backend/media/announcements/ann-entrance-exam.jpg
  backend/media/announcements/blood-donation.png
  backend/media/announcements/carousel-2.png
  backend/media/announcements/carousel-3.png
  backend/media/announcements/grand-iftar.jpg
  backend/media/announcements/juan-more-drop.jpg
  backend/media/events/ched-tech-visit.jpg
  backend/media/events/doctors-meeting.jpg
  backend/media/events/dr-lee-visits-sim-lab.jpg
  backend/media/events/entrance-exam.jpg
  backend/media/events/event-1.jpg
  backend/media/events/event-2.jfif
  backend/media/events/event-2_FzUmRGV.jfif
  backend/media/events/event-3.jpg
  backend/media/events/event-4.jpeg
  backend/media/events/event-4_jysmmRr.jpeg
  backend/media/events/meeting-with-visitors.jpg
  backend/media/events/research-2024.jpg
  backend/media/publications/follicular-dendritic-cell.png
  backend/media/publications/pdfs/C_Cheat_Sheet.pdf
  backend/media/publications/pdfs/catedral-2020-these-are-still-good-days-to-heal-cancer-care-and-the-co_iBmsXAN.pdf
  backend/media/publications/pdfs/follicular-dendritic-cell....pdf
  backend/media/publications/pdfs/receptor-conversion-vocal-cord-paralysis....pdf
  backend/media/publications/pdfs/succinate-dehydrogenase....pdf
  backend/media/publications/postpandrial-peaking....png
  backend/media/publications/vocal-cord-paralysis.png
  frontend/src/components/Publications.jsx
  frontend/src/styles/Main.css
  frontend/src/styles/Main.css.map
  frontend/src/styles/Main.sass
Labels: documentation, testing, content

#126 Added content to 'Admission' page
  frontend/src/assets/images/admission/enrollment.jpg
  frontend/src/assets/images/admission/entrance-exam.jpg
  frontend/src/assets/images/admission/gen-assembly.jpg
  frontend/src/assets/images/admission/hero.jpg
  frontend/src/assets/images/admission/iftar.jpg
  frontend/src/assets/images/admission/intrams.jpg
  frontend/src/assets/images/admission/med-start.png
  frontend/src/assets/images/admission/panel-interview.jpg
  frontend/src/assets/images/admission/payment-fee.jpg
  frontend/src/assets/images/admission/pre-clerkship.png
  frontend/src/assets/images/admission/scholarship.jpg
  frontend/src/assets/images/admission/sim.jpg
  frontend/src/assets/images/admission/student-act.jpg
  frontend/src/components/MonthActivities.jsx
  frontend/src/components/Process.jsx
  frontend/src/components/Scholarship.jsx
  frontend/src/pages/Admission.jsx
  frontend/src/styles/Main.css
  frontend/src/styles/Main.css.map
  frontend/src/styles/Main.sass
Labels: documentation, testing, content

#128 Added content to 'Simulation' page
  backend/media/trainings/adelaide-training.jpg
  backend/media/trainings/doctors-meeting.jpg
  backend/media/trainings/sim-3.jpg
  backend/media/trainings/sim-4.jpg
  backend/media/trainings/singapore.jpg
  backend/media/trainings/training-7.jpg
  backend/media/trainings/training-7_po49YOQ.jpg
  backend/simulation/migrations/0002_alter_trainings_name.py
  backend/simulation/models.py
  frontend/src/assets/images/SAM-sim.jpg
  frontend/src/assets/images/adult-child.jpg
  frontend/src/assets/images/apollo-sim.jpg
  frontend/src/assets/images/ares-sim.jpg
  frontend/src/assets/images/aria-sim.jpg
  frontend/src/assets/images/bg-admission.jpg
  frontend/src/assets/images/bg-img.jpg
  frontend/src/assets/images/birthing.jpg
  frontend/src/assets/images/blood-donation.png
  frontend/src/assets/images/brain-blueprint.jpg
  frontend/src/assets/images/breast.jpg
  frontend/src/assets/images/cells.jpg
  frontend/src/assets/images/cpr.jpg
  frontend/src/assets/images/dentistry.png
  frontend/src/assets/images/dna-under-microscope.jpg
  frontend/src/assets/images/luna-sim.jpg
  frontend/src/assets/images/lung-mri.jpg
  frontend/src/assets/images/lung-x-ray.jpg
  frontend/src/assets/images/matt.jpg
  frontend/src/assets/images/medical-consult.png
  frontend/src/assets/images/simulation/adult-child-cpr.png
  frontend/src/assets/images/simulation/airway-management.png
  frontend/src/assets/images/simulation/apollo.png
  frontend/src/assets/images/simulation/ares.png
  frontend/src/assets/images/simulation/aria.png
  frontend/src/assets/images/simulation/ched.png
  frontend/src/assets/images/simulation/com.png
  frontend/src/assets/images/simulation/cpr.png
  frontend/src/assets/images/simulation/faculty-training.jpg
  frontend/src/assets/images/simulation/hero.png
  frontend/src/assets/images/simulation/intraosseous.png
  frontend/src/assets/images/simulation/luna.png
  frontend/src/assets/images/simulation/sam.png
  frontend/src/assets/images/simulation/sim-1.jpg
  frontend/src/assets/images/simulation/sim-2.jpg
  frontend/src/assets/images/simulation/sim-3.jpg
  frontend/src/assets/images/simulation/up.png
  frontend/src/assets/images/simulation/venipuncture.png
  frontend/src/assets/images/simulation/west-visayas.png
  frontend/src/components/MannequinCards.jsx
  frontend/src/components/SimTraining.jsx
  frontend/src/components/Trainers.jsx
  frontend/src/pages/Simulation.jsx
  frontend/src/styles/Main.css
  frontend/src/styles/Main.css.map
  frontend/src/styles/Main.sass
Labels: documentation, enhancement, content

#129 Added content to 'About' page
  backend/about/migrations/0005_alter_benefactors_name_alter_benefactors_position.py
  backend/about/models.py
  backend/media/benefactors/aragasi.png
  backend/media/benefactors/de-vera.png
  backend/media/benefactors/pia.png
  backend/media/benefactors/student-3.jpg
  backend/media/benefactors/student-4.jpg
  backend/media/benefactors/student-4_OCXCPxe.jpg
  frontend/src/assets/images/about/values.jpg
  frontend/src/components/Values.jsx
  frontend/src/pages/About.jsx
Labels: documentation, testing, content

#130 Added content to 'Others' page
  backend/media/news/event-3_Sy7XvKa.jpg
  backend/media/news/event-4.jpeg
  backend/media/news/grand-iftar.jpg
  backend/media/news/juan-more-drop.jpg
  backend/media/officers/president.jpg
  backend/media/officers/research-committee.jpg
  backend/media/officers/secretary.jpg
  backend/media/officers/student-1_9h4uz6n.jpg
  backend/media/officers/student-2.jpg
  backend/media/officers/student-3.jpg
  backend/media/officers/student-4.jpg
  backend/media/officers/treasurer.jpg
  backend/media/officers/vice-president.jpg
  frontend/src/assets/images/404-icon.png
  frontend/src/assets/images/others/act-1.jpg
  frontend/src/assets/images/others/act-10.jpg
  frontend/src/assets/images/others/act-11.jpg
  frontend/src/assets/images/others/act-2.jpg
  frontend/src/assets/images/others/act-3.jpg
  frontend/src/assets/images/others/act-4.jpg
  frontend/src/assets/images/others/act-5.jpg
  frontend/src/assets/images/others/act-6.jpg
  frontend/src/assets/images/others/act-7.jpg
  frontend/src/assets/images/others/act-8.jpg
  frontend/src/assets/images/others/act-9.jpg
  frontend/src/assets/images/others/sommed-logo.png
  frontend/src/components/Gallery.jsx
  frontend/src/components/Spotlight.jsx
  frontend/src/pages/Faculty.jsx
  frontend/src/pages/NotFound.jsx
  frontend/src/pages/Others.jsx
  frontend/src/styles/404_Page.css
  frontend/src/styles/404_Page.css.map
  frontend/src/styles/404_Page.sass
  frontend/src/styles/Main.css
  frontend/src/styles/Main.css.map
  frontend/src/styles/Main.sass
Labels: documentation, testing, content

#132 Fixed detail page header overflowing 🔧🪲
  frontend/src/styles/Detail.css
  frontend/src/styles/Detail.css.map
  frontend/src/styles/Detail.sass
Labels: bug, enhancement

#133 Adjusted character limit on models 📏
  backend/home/migrations/0002_alter_announcements_title_alter_events_title_and_more.py
  backend/home/models.py
Labels: bug, enhancement

#143 Resized images to fit on 'Announcements' section
  backend/media/announcements/ann-entrance-exam.jpg
  backend/media/announcements/grand-iftar.jpg
  backend/media/announcements/juan-more-drop.jpg
  backend/media/announcements/juan-more-drop.png
  backend/media/announcements/kahayag-kalinaw.png
  backend/media/announcements/trivia-night_lXyQ6y4.png
Labels: bug, enhancement

#144 Added content to section in 'Admission Page' 📕
  backend/.gitignore
  frontend/src/components/MacroButtons.jsx
  frontend/src/components/Scholarship.jsx
  frontend/src/components/Values.jsx
Labels: documentation, testing, content

#147 Added large video file using Git LFS
  .gitattributes
  frontend/.gitignore
  frontend/src/assets/videos/msu-video.mp4
Labels: enhancement, testing

#148 Added large video file using Git LFS
  .gitattributes
  frontend/.gitignore
  frontend/src/assets/videos/msu-video.mp4
Labels: enhancement, testing, production
