Repository DawnBee/college-medicine-app, pull requests merged in 2024-07, with the labels that each got.

#151 Added social media links
  frontend/index.html
  frontend/src/components/Footer.jsx
  frontend/src/components/Spotlight.jsx
  frontend/src/styles/Main.css
  frontend/src/styles/Main.css.map
  frontend/src/styles/Main.sass
Labels: documentation, enhancement, production

#152 Added social media links
  frontend/index.html
  frontend/src/components/Footer.jsx
  frontend/src/components/Spotlight.jsx
  frontend/src/styles/Main.css
  frontend/src/styles/Main.css.map
  frontend/src/styles/Main.sass
Labels: enhancement, production

#155 Fixed date display on 'Activities' component
  backend/backend/settings.py
  frontend/src/components/Activities.jsx
Labels: bug, enhancement, production

#156 Fixed date display on 'Activities' component
  backend/backend/settings.py
  frontend/src/components/Activities.jsx
Labels: bug, enhancement, production

#157 Fixed 'image optimization' error in production 🐞
  backend/about/models.py
  backend/faculty/models.py
  backend/home/models.py
  backend/others/models.py
  backend/requirements.txt
  backend/simulation/models.py
Labels: bug, enhancement, testing, production

#158 Fixed error when uploading images to certain models in production 🔧
  backend/about/models.py
  backend/faculty/models.py
  backend/home/models.py
  backend/others/models.py
  backend/simulation/models.py
Labels: bug, enhancement, production

#159 Changed size limit of images
  backend/home/models.py
  backend/simulation/models.py
Labels: enhancement, testing, production

#160 Changed image size limit
  backend/home/models.py
  backend/simulation/models.py
Labels: enhancement, testing, production

#161 Added testcases to 'Home, About, & Admission' models 🧪
  backend/about/tests.py
  backend/admission/tests.py
  backend/home/tests.py
Labels: documentation, testing, production

#162 Optimized Images and Fixed Typos
  frontend/src/assets/images/admission/hero.jpg
  frontend/src/assets/images/faculty/wooden-theme.png
  frontend/src/assets/images/general/bg-medical.svg
  frontend/src/assets/images/general/com-outline.svg
  frontend/src/assets/images/general/infirm-building.jpg
  frontend/src/assets/images/general/library-2.jpg
  frontend/src/assets/images/general/library-building.jpg
  frontend/src/assets/images/simulation/facility.jpg
  frontend/src/assets/images/simulation/faculty-training.jpg
  frontend/src/assets/images/simulation/hero.png
  frontend/src/components/OfficerCards.jsx
  frontend/src/components/Spotlight.jsx
Labels: enhancement, production

#163 Added test cases, optimized images and fixed typos
  backend/about/tests.py
  backend/admission/tests.py
  backend/home/tests.py
  frontend/src/assets/images/admission/hero.jpg
  frontend/src/assets/images/faculty/wooden-theme.png
  frontend/src/assets/images/general/bg-medical.svg
  frontend/src/assets/images/general/com-outline.svg
  frontend/src/assets/images/general/infirm-building.jpg
  frontend/src/assets/images/general/library-2.jpg
  frontend/src/assets/images/general/library-building.jpg
  frontend/src/assets/images/simulation/facility.jpg
  frontend/src/assets/images/simulation/faculty-training.jpg
  frontend/src/assets/images/simulation/hero.png
  frontend/src/components/OfficerCards.jsx
  frontend/src/components/Spotlight.jsx
Labels: documentation, enhancement, production

#164 Modified size limit for 'Message' image field 📏
  backend/faculty/models.py
Labels: enhancement, production

#165 Modified size limit for 'Message' image field 📏
  backend/faculty/models.py
Labels: enhancement, production
